#!/bin/sh
# prerm script for mosquitto
#
# see: dh_installdeb(1)

set -e

case "$1" in
	remove|purge|deconfigure)
		dpkg-maintscript-helper mv_conffile /etc/mosquitto.conf /etc/mosquitto/mosquitto.conf 0.8.3 -- "$@"
#	initctl stop mosquitto
	echo -n
	;;

	upgrade)
		dpkg-maintscript-helper mv_conffile /etc/mosquitto.conf /etc/mosquitto/mosquitto.conf 0.8.3 -- "$@"
	;;
	failed-upgrade)
	;;

	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
